# Generated by Django 3.0.6 on 2020-07-08 17:40

import Auto_Zdam.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Zdam', '0002_auto_20200628_1130'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Auto_Zdam.models.UserManager()),
            ],
        ),
    ]
