# Generated by Django 3.0.6 on 2020-10-24 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Zdam', '0004_auto_20200709_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='car_brand',
            field=models.CharField(max_length=64, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='car_equipment',
            field=models.ManyToManyField(to='Auto_Zdam.Equip', verbose_name='Wyposażenie'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='car_mileage',
            field=models.IntegerField(verbose_name='Przebieg'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='car_model',
            field=models.CharField(max_length=64, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.IntegerField(choices=[(1, 'osobowe'), (2, 'dostawcze'), (3, 'motocykl')], verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='color',
            field=models.CharField(max_length=64, verbose_name='Kolor'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='doors_number',
            field=models.IntegerField(choices=[(1, '3'), (2, '5')], verbose_name='Liczba drzwi'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='engine_capacity',
            field=models.IntegerField(verbose_name='Pojemność silnika'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='fuel_type',
            field=models.IntegerField(choices=[(1, 'benzyna'), (2, 'diesel'), (3, 'LPG'), (4, 'benzyna/lpg'), (5, 'hybryda'), (6, 'elektryczny')], verbose_name='Rodzaj paliwa'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='photos_2',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='photos_3',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='photos_4',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='photos_5',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.IntegerField(verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='seats_number',
            field=models.IntegerField(choices=[(1, '2'), (2, '4'), (3, '5'), (4, '6')], verbose_name='Liczba siedzeń'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.IntegerField(choices=[(1, 'SUV'), (2, 'sedan'), (3, 'hatchback')], verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Wystawiający'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='year_of_production',
            field=models.SmallIntegerField(verbose_name='Rok produkcji'),
        ),
    ]
